/* The Fires Lab — Copyright (c) 2026 Catherine Lake Creations LLC. All rights reserved.
   Build reference: CLC-RG-7F61363DDFE5 */
/* =========================================================
   Traditional Chinese (繁體中文) for the Fire Mission Sim

   The sim's own dictionary. It is NOT generated by tools/tag-i18n.js and
   that tool must not be pointed at sim.html. Edit the "zh" values here by
   hand; leave a value as "" and the sim shows the English.

   "en" is a copy of the English in the code, for the translator. The code
   is the one home for the English: when the wording changes there, change
   "en" here too and re-check "zh" — test-runtime.js section 46 fails on any
   entry whose "en" no longer matches, so old Chinese is never shown for new
   English.

   Keep every {placeholder} and every HTML entity (&rarr;). \n is a line
   break in the fires log.

   NOT A QUALIFIED TRANSLATION. Written by Claude on 2026-09-28, matched to
   terms already in js/lang-zh.js where they exist (高效益目標清單, 攻擊型
   無人機, 火力協調組, 終期狀態, 彈著時間, 制壓, 砲連 …). The fire-direction
   and radio wording (效力射, 試射, 聽令射擊, 備妥即射, 指定彈著時間, 即將彈著,
   完畢) and the callsigns need the interpreter's review. Grids, target
   numbers (AB1001), WX / TAI / EA names, DELAY LINE RED, system names
   (M109, RT2000, OWA) and class codes (AAV, ZBD, FUEL, ENG, LCU) stay in
   Latin script by design (Lee, 2026-09-28).
   ========================================================= */

window.SIM_LANG_ZH = {

  /* ---------- the timeline ---------- */
  "sim.tl.exit": {
    en: "Exit",
    zh: "離開"
  },
  "sim.tl.label": {
    en: "Timeline",
    zh: "時間軸"
  },
  "sim.tl.pause": {
    en: "Pause",
    zh: "暫停"
  },
  "sim.tl.play": {
    en: "Play",
    zh: "播放"
  },
  "sim.tl.progress": {
    en: "Scenario progress",
    zh: "想定進度"
  },
  "sim.tl.stop": {
    en: "Stop",
    zh: "停止"
  },

  /* ---------- the feed ---------- */
  "sim.feed.alt": {
    en: "Oblique aerial view of the coastline from the drone's point of view.",
    zh: "由無人機視角拍攝的海岸線斜角空照畫面。"
  },
  "sim.feed.modelabel": {
    en: "Sensor mode {m}. Press I to switch.",
    zh: "感測器模式 {m}。按 I 切換。"
  },
  "sim.feed.modetitle": {
    en: "Sensor mode — click or press I",
    zh: "感測器模式 — 點擊或按 I"
  },

  /* ---------- the overlay on the feed ---------- */
  "sim.hud.acrft": {
    en: "ACRFT",
    zh: "載機"
  },
  "sim.hud.north": {
    en: "N",
    zh: "北"
  },
  "sim.tag.obs": {
    en: "OBS {n}",
    zh: "障礙 {n}"
  },
  "sim.tag.open": {
    en: "{name} OPEN",
    zh: "{name} 已開通"
  },
  "sim.tag.opening": {
    en: "{name} OPENING",
    zh: "{name} 開闢中"
  },
  "sim.tag.stopped": {
    en: "{cls} STOPPED",
    zh: "{cls} 已擊停"
  },

  /* ---------- the brief ---------- */
  "sim.brief.begin": {
    en: "Begin &rarr;",
    zh: "開始 &rarr;"
  },
  "sim.brief.beginlabel": {
    en: "Close the brief and begin",
    zh: "關閉簡報並開始"
  },
  "sim.brief.close": {
    en: "Close the brief",
    zh: "關閉簡報"
  },
  "sim.brief.eff.h": {
    en: "Effects",
    zh: "效果"
  },
  "sim.brief.eff1": {
    en: "Engineering vehicles are unable to move",
    zh: "工兵車輛無法移動"
  },
  "sim.brief.eff2": {
    en: "Fuel logistics vehicles are destroyed",
    zh: "油料後勤車輛遭摧毀"
  },
  "sim.brief.end": {
    en: "The enemy is unable to mass significant combat power west of DELAY LINE RED.",
    zh: "敵軍無法於 DELAY LINE RED 以西集結顯著戰力。"
  },
  "sim.brief.end.h": {
    en: "End state",
    zh: "終期狀態"
  },
  "sim.brief.hptl.h": {
    en: "High Payoff Target List",
    zh: "高效益目標清單"
  },
  "sim.brief.hptl1": {
    en: "Engineering Vehicles",
    zh: "工兵車輛"
  },
  "sim.brief.hptl2": {
    en: "Fuel Vehicles",
    zh: "油料車輛"
  },
  "sim.brief.hptl3": {
    en: "Amphibious Assault Vehicles",
    zh: "兩棲突擊車"
  },
  "sim.brief.intent": {
    en: "Keep as many enemy amphibious vehicles as possible east of DELAY LINE RED, for as long as possible, so our maneuver forces have time to reinforce the key terrain to the west.",
    zh: "盡可能將最多的敵軍兩棲車輛阻滯於 DELAY LINE RED 以東，且時間越長越好，使我方機動部隊有時間增援西側的關鍵地形。"
  },
  "sim.brief.intent.h": {
    en: "Commander’s intent",
    zh: "指揮官企圖"
  },
  "sim.brief.key.open": {
    en: "Unrestricted",
    zh: "非限制地形"
  },
  "sim.brief.key.restricted": {
    en: "Restricted",
    zh: "限制地形"
  },
  "sim.brief.map.alt": {
    en: "The operation map: grid, obstacles, engagement areas, target areas and preplanned targets.",
    zh: "作戰地圖：方格、障礙、接戰地區、目標區與預劃目標。"
  },
  "sim.brief.mission": {
    en: "At T - 0, 77th Combined Arms Brigade delays the enemy amphibious assault east of DELAY LINE RED in order to allow friendly maneuver forces time to reinforce key terrain west of the objective area.",
    zh: "於 T-0 時，第 77 聯兵旅於 DELAY LINE RED 以東遲滯敵軍兩棲突擊，以爭取時間，使友軍機動部隊增援目標區以西的關鍵地形。"
  },
  "sim.brief.mission.h": {
    en: "Mission",
    zh: "任務"
  },
  "sim.brief.next": {
    en: "Next slide",
    zh: "下一張"
  },
  "sim.brief.obj.h": {
    en: "Objectives",
    zh: "作戰目標"
  },
  "sim.brief.obj1": {
    en: "Disrupt enemy’s ability to breach our obstacles, containing the enemy to the area around the beach where we can continue to fire upon him.",
    zh: "瓦解敵軍突破我方障礙的能力，將敵軍限制於海灘周邊地區，使我方得以持續對其射擊。"
  },
  "sim.brief.obj2": {
    en: "Degrade the enemy’s ability to refuel, limiting the range of their assault vehicles which the enemy relies upon for maneuver.",
    zh: "削弱敵軍的加油能力，限制其賴以機動之突擊車輛的行動範圍。"
  },
  "sim.brief.prev": {
    en: "Previous slide",
    zh: "上一張"
  },
  "sim.brief.sub.map": {
    en: "Map",
    zh: "地圖"
  },
  "sim.brief.sub.terrain-analysis": {
    en: "Terrain analysis",
    zh: "地形分析"
  },
  "sim.brief.terrain.alt": {
    en: "Map of the objective area with restricted terrain hatched in red.",
    zh: "目標區地圖，限制地形以紅色斜線標示。"
  },
  "sim.brief.title": {
    en: "Operation Iron Gate",
    zh: "鐵門作戰"
  },

  /* ---------- the dock ---------- */
  "sim.dock.assets": {
    en: "Asset status board",
    zh: "火力單位狀態板"
  },
  "sim.dock.chat": {
    en: "Fires coordination chat",
    zh: "火力協調通信"
  },
  "sim.dock.missions": {
    en: "Active missions",
    zh: "執行中任務"
  },

  /* ---------- the net: the opening radio check ---------- */
  "sim.chat.open1": {
    en: "All stations, this is Dragonfire FSCC, radio check, over.",
    zh: "各台，這裡是火龍火力協調組，通信測試，完畢。"
  },
  "sim.chat.open2": {
    en: "Dragonfire FSCC, this is Steel Rain, roger, loud and clear, over.",
    zh: "火龍火力協調組，這裡是鋼雨，收到，收聽清晰，完畢。"
  },
  "sim.chat.open3": {
    en: "Dragonfire FSCC, this is Anvil, all firing units are up and laid, over.",
    zh: "火龍火力協調組，這裡是鐵砧，所有射擊單位已完成放列標定，完畢。"
  },

  /* ---------- the net: every transmission ---------- */
  "sim.fire": {
    en: "FIRE",
    zh: "射擊"
  },
  "sim.prompt.label": {
    en: "Fire {id}, {unit}",
    zh: "射擊 {id}，{unit}"
  },
  "sim.prompt.post": {
    en: ", over.",
    zh: "，完畢。"
  },
  "sim.prompt.pre": {
    en: "{unit}, this is {obs}, {id}, ",
    zh: "{unit}，這裡是{obs}，{id}，"
  },
  "sim.say.body.rockets": {
    en: "{id}, {n} rockets {shell}",
    zh: "{id}，{shell}火箭 {n} 枚"
  },
  "sim.say.body.rounds": {
    en: "{id}, {n} rounds {shell}",
    zh: "{id}，{shell} {n} 發"
  },
  "sim.say.cff": {
    en: "{unit}, this is {obs}, {type}. {where}. {count} {target} {env}. {shell}. {control}{tot}, over.",
    zh: "{unit}，這裡是{obs}，{type}。{where}。{target}目標 {count} 個，位於{env}。{shell}。{control}{tot}，完畢。"
  },
  "sim.say.cffdrone": {
    en: "{unit}, this is {obs}, {drones}. {where}. Seek {count} {target} {env}, over.",
    zh: "{unit}，這裡是{obs}，{drones}。{where}。搜索{target}目標 {count} 個，位於{env}，完畢。"
  },
  "sim.say.droneaway": {
    en: "{head} {id}, drones away, over.",
    zh: "{head}{id}，無人機已發射，完畢。"
  },
  "sim.say.fire": {
    en: "{unit}, this is {obs}, {id}, fire, over.",
    zh: "{unit}，這裡是{obs}，{id}，射擊，完畢。"
  },
  "sim.say.head": {
    en: "{obs}, this is {unit},",
    zh: "{obs}，這裡是{unit}，"
  },
  "sim.say.latetot": {
    en: "{head} unable. Time on target {tot} is inside time of flight — earliest is {earliest}. Send a later time on target, over.",
    zh: "{head}無法執行。彈著時間 {tot} 短於飛行時間 — 最早為 {earliest}。請送出較晚的彈著時間，完畢。"
  },
  "sim.say.mto": {
    en: "{head} {body}, time of flight {tof} seconds, over.",
    zh: "{head}{body}，飛行時間 {tof} 秒，完畢。"
  },
  "sim.say.mtodrone": {
    en: "{head} {id}, {drones}, one every {sec} seconds, time of flight {min} minutes, over.",
    zh: "{head}{id}，{drones}，每 {sec} 秒發射一架，飛行時間 {min} 分鐘，完畢。"
  },
  "sim.say.mtohold": {
    en: "{head} {body}, time of flight {tof} seconds. Ready, at your command, over.",
    zh: "{head}{body}，飛行時間 {tof} 秒。準備完畢，聽令射擊，完畢。"
  },
  "sim.say.mtotot": {
    en: "{head} {body}, time on target {tot}, time of flight {tof} seconds, over.",
    zh: "{head}{body}，彈著時間 {tot}，飛行時間 {tof} 秒，完畢。"
  },
  "sim.say.noammo": {
    en: "{obs}, this is {unit}, unable — insufficient ammunition, {left} rounds remaining, {need} required, over.",
    zh: "{obs}，這裡是{unit}，無法執行 — 彈藥不足，剩餘 {left} 發，需要 {need} 發，完畢。"
  },
  "sim.say.nodrones": {
    en: "{obs}, this is {unit}, unable — insufficient drones, {left} remaining, {need} requested, over.",
    zh: "{obs}，這裡是{unit}，無法執行 — 無人機不足，剩餘 {left} 架，請求 {need} 架，完畢。"
  },
  "sim.say.shot": {
    en: "{head} {id}, shot, over.",
    zh: "{head}{id}，已發射，完畢。"
  },
  "sim.say.splash": {
    en: "{head} {id}, splash, over.",
    zh: "{head}{id}，即將彈著，完畢。"
  },
  "sim.typing": {
    en: "is typing",
    zh: "正在輸入"
  },
  "sim.where.grid": {
    en: "Grid {grid}",
    zh: "座標 {grid}"
  },
  "sim.where.target": {
    en: "Target {wx}",
    zh: "目標 {wx}"
  },

  /* ---------- callsigns (display only — the engine keys on the English) ---------- */
  "sim.cs.anvil": {
    en: "Anvil",
    zh: "鐵砧"
  },
  "sim.cs.dragonfire-fscc": {
    en: "Dragonfire FSCC",
    zh: "火龍火力協調組"
  },
  "sim.cs.fire-storm": {
    en: "Fire Storm",
    zh: "火風暴"
  },
  "sim.cs.lightning": {
    en: "Lightning",
    zh: "閃電"
  },
  "sim.cs.predator": {
    en: "Predator",
    zh: "掠食者"
  },
  "sim.cs.steel-rain": {
    en: "Steel Rain",
    zh: "鋼雨"
  },
  "sim.cs.typhoon": {
    en: "Typhoon",
    zh: "颱風"
  },

  /* ---------- the call for fire ---------- */
  "sim.cff.control": {
    en: "Method of control",
    zh: "射擊控制方式"
  },
  "sim.cff.count": {
    en: "Number of targets",
    zh: "目標數量"
  },
  "sim.cff.dronenote": {
    en: "Drones launch when you send this mission.",
    zh: "送出此任務後，無人機即發射。"
  },
  "sim.cff.drones": {
    en: "Number of drones",
    zh: "無人機數量"
  },
  "sim.cff.east": {
    en: "Easting, three to five digits",
    zh: "東距，三至五位數"
  },
  "sim.cff.env": {
    en: "Environment",
    zh: "環境"
  },
  "sim.cff.label": {
    en: "Fire mission",
    zh: "射擊任務"
  },
  "sim.cff.north": {
    en: "Northing, three to five digits",
    zh: "北距，三至五位數"
  },
  "sim.cff.or": {
    en: "or",
    zh: "或"
  },
  "sim.cff.pre": {
    en: "Preplanned target or area",
    zh: "預劃目標或區域"
  },
  "sim.cff.send": {
    en: "Send",
    zh: "送出"
  },
  "sim.cff.shell": {
    en: "Method of engagement",
    zh: "接戰方式"
  },
  "sim.cff.target": {
    en: "Target type",
    zh: "目標類型"
  },
  "sim.cff.thisis": {
    en: "this is Dragonfire FSCC",
    zh: "這裡是火龍火力協調組"
  },
  "sim.cff.tot": {
    en: "Time on target, minutes and seconds",
    zh: "彈著時間，分與秒"
  },
  "sim.cff.type": {
    en: "Type of mission",
    zh: "任務類型"
  },
  "sim.cff.unit": {
    en: "Unit called",
    zh: "呼叫單位"
  },
  "sim.pre.area": {
    en: "Grid (or pick an area)",
    zh: "座標（或選擇區域）"
  },
  "sim.pre.noarea": {
    en: "No TAI or EA drawn",
    zh: "未劃設 TAI 或 EA"
  },
  "sim.pre.notarget": {
    en: "No preplanned targets",
    zh: "無預劃目標"
  },
  "sim.pre.target": {
    en: "Preplanned target",
    zh: "預劃目標"
  },

  /* ---------- the call for fire: method of control ---------- */
  "sim.ctl.at-my-command": {
    en: "At my command",
    zh: "聽令射擊"
  },
  "sim.ctl.time-on-target": {
    en: "Time on target",
    zh: "指定彈著時間"
  },
  "sim.ctl.when-ready": {
    en: "When ready",
    zh: "備妥即射"
  },

  /* ---------- the call for fire: type of mission ---------- */
  "sim.mt.adjust-fire": {
    en: "Adjust fire",
    zh: "試射"
  },
  "sim.mt.fire-for-effect": {
    en: "Fire for effect",
    zh: "效力射"
  },
  "sim.mt.immediate-suppression": {
    en: "Immediate suppression",
    zh: "立即制壓"
  },
  "sim.mt.suppression": {
    en: "Suppression",
    zh: "制壓射擊"
  },

  /* ---------- the call for fire: munitions ---------- */
  "sim.mun.high-explosive": {
    en: "High explosive",
    zh: "高爆彈"
  },
  "sim.mun.one-way-attack-uas": {
    en: "One Way Attack UAS",
    zh: "攻擊型無人機"
  },
  "sim.mun.spoken.high-explosive": {
    en: "high explosive",
    zh: "高爆彈"
  },
  "sim.mun.spoken.one-way-attack-uas": {
    en: "one-way attack UAS",
    zh: "攻擊型無人機"
  },

  /* ---------- the call for fire: target type ---------- */
  "sim.class.amphibious-assault-vehicle": {
    en: "amphibious assault vehicle",
    zh: "兩棲突擊車"
  },
  "sim.class.engineering": {
    en: "engineering",
    zh: "工兵車輛"
  },
  "sim.class.landing-craft": {
    en: "landing craft",
    zh: "登陸艇"
  },
  "sim.class.logistics": {
    en: "logistics",
    zh: "後勤車輛"
  },
  "sim.class.self-propelled-artillery": {
    en: "self propelled artillery",
    zh: "自走砲"
  },

  /* ---------- the call for fire: environment ---------- */
  "sim.env.in-the-open": {
    en: "in the open",
    zh: "開闊地"
  },
  "sim.env.in-the-urban-environment": {
    en: "in the urban environment",
    zh: "城鎮地區"
  },
  "sim.env.in-the-water": {
    en: "in the water",
    zh: "水中"
  },

  /* ---------- drone counts ---------- */
  "sim.drone.many": {
    en: "{n} drones",
    zh: "{n} 架無人機"
  },
  "sim.drone.one": {
    en: "{n} drone",
    zh: "{n} 架無人機"
  },

  /* ---------- refusals under the Send button ---------- */
  "sim.err.backat": {
    en: "back on the air {t}",
    zh: "將於 {t} 恢復"
  },
  "sim.err.earliest": {
    en: "Unable: earliest TOT is {t}.",
    zh: "無法執行：最早彈著時間為 {t}。"
  },
  "sim.err.griddigits": {
    en: "Grid needs three, four or five digits each.",
    zh: "座標東距與北距各需三、四或五位數。"
  },
  "sim.err.griddigitsarea": {
    en: "Grid needs three, four or five digits each — or pick a TAI / EA.",
    zh: "座標東距與北距各需三、四或五位數，或選擇一個 TAI / EA。"
  },
  "sim.err.holding": {
    en: "still holding {id}",
    zh: "仍在待命 {id}"
  },
  "sim.err.noammo": {
    en: "{unit}: insufficient ammunition — {have} rounds remaining, {need} required.",
    zh: "{unit}：彈藥不足，剩餘 {have} 發，需要 {need} 發。"
  },
  "sim.err.noarea": {
    en: "That area is not in the scenario.",
    zh: "此區域不在想定中。"
  },
  "sim.err.nodronemod": {
    en: "Drones are not loaded.",
    zh: "無人機模組未載入。"
  },
  "sim.err.nodrones": {
    en: "{unit}: insufficient drones — {left} remaining, {n} requested.",
    zh: "{unit}：無人機不足，剩餘 {left} 架，請求 {n} 架。"
  },
  "sim.err.nosalvos": {
    en: "{unit} is unavailable — no salvos remaining.",
    zh: "{unit}無法運用，已無剩餘齊射。"
  },
  "sim.err.offfeed": {
    en: "{grid} is outside the feed.",
    zh: "{grid} 位於畫面之外。"
  },
  "sim.err.parse": {
    en: "That grid does not parse.",
    zh: "無法解析此座標。"
  },
  "sim.err.totformat": {
    en: "Time on target needs a clock time, as MM:SS.",
    zh: "彈著時間需為時鐘時間，格式為 MM:SS。"
  },
  "sim.err.totneeded": {
    en: "Time on target needs a time.",
    zh: "彈著時間需要填入時間。"
  },
  "sim.err.unavailable": {
    en: "{unit} is unavailable — {when}.",
    zh: "{unit}無法運用，{when}。"
  },
  "sim.err.uneven": {
    en: "Uneven grid: {e} digits then {n}.",
    zh: "座標位數不一致：東距 {e} 位，北距 {n} 位。"
  },

  /* ---------- the asset status board ---------- */
  "sim.as.back": {
    en: "{sys} · back {t}",
    zh: "{sys} · {t} 恢復"
  },
  "sim.as.drone": {
    en: "{n} drone",
    zh: "{n} 架"
  },
  "sim.as.drones": {
    en: "{n} drones",
    zh: "{n} 架"
  },
  "sim.as.dronesof": {
    en: "{n} of {max} drones",
    zh: "{n} / {max} 架無人機"
  },
  "sim.as.hint": {
    en: "{n} of {total} ready",
    zh: "{n} / {total} 就緒"
  },
  "sim.as.holding": {
    en: "{sys} · holding {id}",
    zh: "{sys} · 待命 {id}"
  },
  "sim.as.rds": {
    en: "{n} rds",
    zh: "{n} 發"
  },
  "sim.as.rdsof": {
    en: "{n} of {max} rounds",
    zh: "{n} / {max} 發"
  },
  "sim.as.salvo": {
    en: "{n} salvo",
    zh: "{n} 次齊射"
  },
  "sim.as.salvos": {
    en: "{n} salvos",
    zh: "{n} 次齊射"
  },
  "sim.as.salvosof": {
    en: "{n} of {max} salvos",
    zh: "{n} / {max} 次齊射"
  },
  "sim.as.spent": {
    en: "{sys} · spent",
    zh: "{sys} · 已用罄"
  },

  /* ---------- active missions ---------- */
  "sim.ms.active": {
    en: "{n} active",
    zh: "{n} 項執行中"
  },
  "sim.ms.drones": {
    en: "{unit} ({sys}) · {n} drones · {grid}",
    zh: "{unit}（{sys}）· {n} 架無人機 · {grid}"
  },
  "sim.ms.empty": {
    en: "No missions sent.",
    zh: "尚未送出任務。"
  },
  "sim.ms.none": {
    en: "None",
    zh: "無"
  },
  "sim.ms.rounds": {
    en: "{unit} ({sys}) · {n} rds · {grid}",
    zh: "{unit}（{sys}）· {n} 發 · {grid}"
  },

  /* ---------- active missions: state ---------- */
  "sim.st.awaiting": {
    en: "Ready — at your command",
    zh: "準備完畢 — 聽令射擊"
  },
  "sim.st.complete": {
    en: "Complete",
    zh: "完成"
  },
  "sim.st.dronesaway": {
    en: "Drones away — first on station {t}",
    zh: "無人機已發射 — 首架 {t} 抵達"
  },
  "sim.st.dronesdone": {
    en: "Drones — {n} of {total} done",
    zh: "無人機 — 已完成 {n} / {total}"
  },
  "sim.st.firing": {
    en: "Firing {t}",
    zh: "{t} 射擊"
  },
  "sim.st.impacting": {
    en: "Impacting — volley {n} of {total}",
    zh: "彈著中 — 第 {n} / {total} 群"
  },
  "sim.st.inflight": {
    en: "In flight — splash {t}",
    zh: "飛行中 — {t} 彈著"
  },
  "sim.st.sending": {
    en: "Sent — awaiting acknowledgement",
    zh: "已送出 — 等待回覆"
  },
  "sim.st.tot": {
    en: "TOT {t}",
    zh: "彈著時間 {t}"
  },

  /* ---------- the fires log ---------- */
  "sim.fl.dive": {
    en: "dive",
    zh: "俯衝"
  },
  "sim.fl.dronesum": {
    en: "{id} {unit} — {n} drones:\n  {tail}",
    zh: "{id} {unit} — {n} 架無人機：\n  {tail}"
  },
  "sim.fl.lost": {
    en: ", {n} lost",
    zh: "，{n} 架損失"
  },
  "sim.fl.nonesum": {
    en: "{id} {unit} — no vehicles inside impact area",
    zh: "{id} {unit} — 彈著區內無車輛"
  },
  "sim.fl.notarget": {
    en: "{id}/{v} no target found",
    zh: "{id}/{v} 未發現目標"
  },
  "sim.fl.note.in-water": {
    en: "in water",
    zh: "在水中"
  },
  "sim.fl.note.rounds-in-water": {
    en: "rounds in water",
    zh: "彈落水中"
  },
  "sim.fl.nothing": {
    en: "nothing struck",
    zh: "未擊中任何目標"
  },
  "sim.fl.novehicles": {
    en: "{id}/{v} no vehicles in the impact area",
    zh: "{id}/{v} 彈著區內無車輛"
  },
  "sim.fl.partsstopped": {
    en: "{parts} stopped",
    zh: "擊停 {parts}"
  },
  "sim.fl.stopped": {
    en: "STOPPED",
    zh: "擊停"
  },
  "sim.fl.sum": {
    en: "{id} {unit} — {n} inside impact area:\n  {parts} stopped",
    zh: "{id} {unit} — 彈著區內 {n} 輛：\n  擊停 {parts}"
  },
  "sim.fl.survived": {
    en: "SURVIVED",
    zh: "倖存"
  },
  "sim.fl.title": {
    en: "Fires log",
    zh: "火力紀錄"
  },

  /* ---------- the score ---------- */
  "sim.sc.fuel": {
    en: "waiting for fuel",
    zh: "等待加油"
  },
  "sim.sc.kills": {
    en: "Stopped: ZBD {zbd} · FUEL {fuel} · ENG {eng}",
    zh: "擊停：ZBD {zbd} · FUEL {fuel} · ENG {eng}"
  },
  "sim.sc.moving": {
    en: "on the move",
    zh: "行進中"
  },
  "sim.sc.obstacles": {
    en: "held at obstacles",
    zh: "受阻於障礙"
  },
  "sim.sc.stopped": {
    en: "stopped by fires",
    zh: "遭火力擊停"
  },
  "sim.sc.title": {
    en: "ZBD through {line}",
    zh: "ZBD 通過 {line}"
  },
  "sim.sc.where": {
    en: "Where the other {n} are:",
    zh: "其餘 {n} 輛位置："
  },

  /* ---------- the map ---------- */
  "sim.map.alt": {
    en: "Gridded overhead map of the engagement area, 20Q KF, with obstacle belts and target areas of interest marked.",
    zh: "接戰地區方格俯視圖，20Q KF，標示障礙帶與目標關注區。"
  },
  "sim.map.label": {
    en: "Engagement area map",
    zh: "接戰地區地圖"
  },
  "sim.rail.map": {
    en: "MAP",
    zh: "地圖"
  },
  "sim.rail.maptitle": {
    en: "Engagement area map (M)",
    zh: "接戰地區地圖 (M)"
  },

  /* ---------- narrow screens ---------- */
  "sim.narrow": {
    en: "The Fire Mission Sim needs a wider screen. Open it on a laptop or a tablet in landscape.",
    zh: "火力任務模擬需要較寬的螢幕。請在筆電或橫向放置的平板上開啟。"
  },

  /* ---------- the Stop question ---------- */
  "sim.confirm.cancel": {
    en: "Cancel",
    zh: "取消"
  },
  "sim.confirm.reset": {
    en: "Yes, reset",
    zh: "是，重設"
  },
  "sim.confirm.text": {
    en: "This resets the simulation, are you sure?",
    zh: "這將重設模擬，確定嗎？"
  }
};
